### ISSUE TITLE
1. Overlay doesnt show 2. touch button doesn't work

### ISSUE THREAD

**Issue by tayser1** [MikeCoder96/chiaki-custom#1]
Thank you for this 
1. The problem with the Overlay still persist. Only shows for a short time after stream starts then disappears -> cant toggle screen button 

2. The touch button of the ps4 controller doesn't work in the app.

**Comment by MikeCoder96** [comment]
Thanks for reporting me.
I want to know:
- which version of android are you using
- device

Are also you able to compile and debug?

**Comment by tayser1** [comment]
> Thanks for reporting me. I want to know:
> 
>     * which version of android are you using
> 
>     * device
> 
> 
> Are also you able to compile and debug?

Samsung Galaxy Z Fold2 
Android 13

how to show the Overlay again? I'm clicking holding sliding and other things and it doesn't show me the Overlay while streaming.

**Comment by MikeCoder96** [comment]
the overlay is not actually working. It need to be reworked.
About your touch button, the only thing that does not work is the button or the entire touch?

EDIT: You can hide buttons screen from settings.

**Comment by tayser1** [comment]
The PS4 controller has a touch field and can be pressed as well. Both don't get recognized.

**Comment by MikeCoder96** [comment]
> The PS4 controller has a touch field and can be pressed as well. Both don't get recognized.

The problem can be the input type that come from PS4 controller. Probably the touchpad is recognized as [SOURCE_MOUSE](https://developer.android.com/reference/android/view/InputDevice#SOURCE_MOUSE)
Due to the fact that I don't own a PS4 Controller, I can't fix this possible issue alone so you can check it by yourself [debugging the right method](https://github.com/MikeCoder96/chiaki-custom/blob/main/android/app/src/main/java/com/metallic/chiaki/session/StreamInput.kt?plain=1#L192-L276)

**Comment by MikeCoder96** [comment]
I'm dropping support for this project, please use [PSPlay](https://www.reddit.com/r/PSPlay/) instead. Support the developer.
